trigger:
- main

pool:
  name: dockeragent

steps:

- powershell: |
    Write-Host "Checking Docker Version..."
    docker version
  displayName: 'Verify Docker'

- powershell: |
    Write-Host "Building Docker Image..."
    docker build -t school-website:latest .
  displayName: 'Build Docker Image'

- powershell: |
    Write-Host "Stopping Existing Container..."
    
    $container = docker ps -aq -f "name=school-app"

    if ($container) {
        docker stop school-app
        docker rm school-app
    }

    Write-Host "Old Container Removed"
  displayName: 'Remove Old Container'

- powershell: |
    Write-Host "Starting New Container..."

    docker run -d `
      --name school-app `
      -p 8080:80 `
      school-website:latest
  displayName: 'Run Docker Container'

- powershell: |
    Write-Host "Running Containers"
    docker ps
  displayName: 'Verify Container'

- powershell: |
    Write-Host "Application URL:"
    Write-Host "http://localhost:8080"
  displayName: 'Display URL'